name: gosdk
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
    # Install all the dependencies
    - name: Install dependencies
      run: |
        echo "running command"
        make build-tools
    - name: Install go
      run: |
        make install
